import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#0e1323",
        "surface-dim": "#0e1323",
        "surface-bright": "#34394a",
        "surface-container-lowest": "#080d1d",
        "surface-container-low": "#161b2b",
        "surface-container": "#1a1f30",
        "surface-container-high": "#25293a",
        "surface-container-highest": "#2f3446",
        "on-surface": "#dee1f9",
        "on-surface-variant": "#c3c5d7",
        "inverse-surface": "#dee1f9",
        "inverse-on-surface": "#2b3041",
        outline: "#8d90a0",
        "outline-variant": "#434654",
        "surface-tint": "#b5c4ff",
        primary: "#b5c4ff",
        "on-primary": "#00297b",
        "primary-container": "#648aff",
        "on-primary-container": "#00236d",
        "inverse-primary": "#1a53d6",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        tertiary: "#4ae176",
        "on-tertiary": "#003915",
        "tertiary-container": "#00a74b",
        "on-tertiary-container": "#003111",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0e1323",
        "on-background": "#dee1f9",
        "surface-variant": "#2f3446",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        gutter: "0.75rem",
        "gutter-mobile": "0.5rem",
        margin: "1rem",
        "margin-mobile": "0.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Mono", "monospace"],
        "body-md": ["Space Mono", "monospace"],
        "body-sm": ["Space Mono", "monospace"],
        "label-lg": ["Space Mono", "monospace"],
        "label-md": ["Space Mono", "monospace"],
        "code-dense": ["Space Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-lg": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-md": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "code-dense": ["10px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
