import type { FastifyInstance } from "fastify";

/**
 * Ensures every response carries the request/correlation id back to the
 * caller, whether it was supplied by the client or generated by the server.
 */
export function registerRequestContext(app: FastifyInstance): void {
  app.addHook("onSend", async (request, reply, payload) => {
    reply.header("x-request-id", request.id);
    return payload;
  });
}
